DROP TABLE PRODUCT;
CREATE TABLE PRODUCT (
     ID VARCHAR(255),
     NAME VARCHAR(500),
     DESCRIPTION TEXT,
     REGULAR_PRICE DECIMAL,
     SALE_PRICE DECIMAL,
     IMAGE_URL TEXT,
     AVAILABLE_QUANTITY INTEGER,
     START_DATE TIMESTAMP,
     END_DATE TIMESTAMP
   );
